name: CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
  
  CD: 
    name: Continuous Delivery
    runs-on: ubuntu-latest

    needs: CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EAS_EXPO_TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Get config file
        env: 
          GOOGLE_SERVICES_64: ${{ secrets.EAS_GOOGLE_PLAY_API }}
        run: |
          echo $GOOGLE_SERVICES_64 > google-services.json.b64
          base64 -d -i google-services.json.b64 > google-services.json

      - name: Build APK with EAS
        run: |
          EXPO_APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.EAS_APPLE_APP_SPECIFIC_PASSWORD }} \
          eas build --platform android --profile preview --non-interactive --no-wait

      - name: Download APK from EAS
        run: |
          mkdir -p artifacts
          mv $(ls -t | grep ".apk" | head -n1) artifacts/app-release.apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: artifacts/app-release.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref_name }}"
          body: "Nova versão disponível! 🚀"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
